// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Calculate(arg1:string,arg2:number,arg3:number):Promise<string>;

export function Clear():Promise<string>;
